name: Deploy to Vercel

on: [push]

jobs:
  setup-environment:
    name: Setup environment
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: yarn
      - run: yarn lint:code

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: yarn
      - run: yarn lint:types

  tests-coverage:
    name: Test & Coverage Report
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [lint, types] # only run after lint and tsc completed successfully
    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: yarn
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          NEXT_PUBLIC_ENABLED_LANGUAGES: en,de
          NEXT_PUBLIC_FALLBACK_LANGUAGE: en
          NEXT_PUBLIC_ENABLED_PROVIDER: local,github,google,facebook,discord
          NEXT_PUBLIC_SESSION_LIFETIME: 28800
          NODE_ENV: test
        with:
          coverageCommand: yarn test:coverage

  # https://github.com/amondnet/vercel-action
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    # on every branch that isnt master
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          # SET THIS 👇 OR YOU WILL DEPLOY TO YOUR PERSONAL VERCEL NAMESPACE
          # scope: ${{ secrets.VERCEL_TEAM_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comments: true

  # https://github.com/amondnet/vercel-action
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # only deploy given successful tests
    needs: tests-coverage
    # on master exclusively
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          # SET THIS 👇 OR YOU WILL DEPLOY TO YOUR PERSONAL VERCEL NAMESPACE
          # scope: ${{ secrets.VERCEL_TEAM_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: true
          vercel-args: '--prod'

  # https://github.com/getsentry/action-release
  sentry-release:
    name: Create Sentry Release
    runs-on: ubuntu-latest
    needs: deploy-prod
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_LOG_LEVEL: debug
    steps:
      - uses: getsentry/action-release@v1.0.1
        with:
          environment: production
          sourcemaps: './_next'
