name: Deploy to production on Vercel

on:
  push:
    branches:
      - 'master'

jobs:
  setup-environment:
    name: Setup deployment environment
    runs-on: ubuntu-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v1
      - run: yarn
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn lint
  tsc:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn tsc
  run-tests-coverage:
    name: Run tests coverage and send report to Code Climate
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [lint, tsc] # only run after lint and tsc completed successfully
    steps:
      - uses: actions/checkout@v1
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          NEXT_PUBLIC_ENABLED_LANGUAGES: en,de
          NEXT_PUBLIC_ENABLED_PROVIDER: local,github,google,facebook,discord
          NEXT_PUBLIC_SESSION_LIFETIME: 28800
          SESSION_COOKIE_SECRET: this-is-a-secret-value-with-at-least-32-characters
          NODE_ENV: test
        with:
          coverageCommand: yarn test:ci
